Document: browseradapter
Title: Debian browseradapter Manual
Author: <insert document author here>
Abstract: This manual describes what browseradapter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/browseradapter/browseradapter.sgml.gz

Format: postscript
Files: /usr/share/doc/browseradapter/browseradapter.ps.gz

Format: text
Files: /usr/share/doc/browseradapter/browseradapter.text.gz

Format: HTML
Index: /usr/share/doc/browseradapter/html/index.html
Files: /usr/share/doc/browseradapter/html/*.html
